# Generated by Django 4.2.17 on 2025-01-07 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sadatabase', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='Development_owner',
            new_name='Development_Owner',
        ),
    ]
