# Generated by Django 4.2.17 on 2025-01-07 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sadatabase', '0002_rename_development_owner_application_development_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='Census_tract',
            new_name='Census_Tract',
        ),
    ]
