# Generated by Django 4.2.17 on 2025-01-07 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sadatabase', '0003_rename_census_tract_application_census_tract'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='Force_majeure_Number',
            new_name='Force_Majeure_Number',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='Force_majeure_Year',
            new_name='Force_Majeure_Year',
        ),
    ]
