# Generated by Django 4.2.17 on 2025-04-24 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sadatabase', '0004_rename_force_majeure_number_application_force_majeure_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='LIHTC_Units',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='MR_Units',
            field=models.CharField(blank=True, default=0, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='Total_Units',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
