# Generated by Django 4.2.17 on 2025-05-13 15:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sadatabase', '0005_alter_application_lihtc_units_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='Last_Updated',
            field=models.DateField(blank=True, default=datetime.date(2025, 5, 13), null=True),
        ),
    ]
