# Generated by Django 4.2.17 on 2025-05-13 15:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sadatabase', '0006_alter_application_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='Last_Updated',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
