# Generated by Django 4.2.17 on 2025-05-13 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sadatabase', '0007_alter_application_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='Last_Updated',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('development_name', models.CharField(max_length=100)),
                ('field_name', models.CharField(max_length=100)),
                ('date', models.DateField(blank=True, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sadatabase.application')),
            ],
        ),
    ]
