# Generated by Django 4.2.17 on 2025-05-14 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sadatabase', '0008_alter_application_last_updated_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='google_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
