# Generated by Django 4.2.17 on 2025-05-20 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sadatabase', '0009_event_google_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='Dev_Owner',
            new_name='Dev_Owner_Phone',
        ),
    ]
