# Generated by Django 4.2.17 on 2025-05-20 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sadatabase', '0010_rename_dev_owner_application_dev_owner_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='Dev_Owner_Phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='Pre_Part_Entities',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
