# Generated by Django 4.2.17 on 2025-05-20 22:37

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('sadatabase', '0011_alter_application_dev_owner_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='Pre_Part_Entities',
            field=django_mysql.models.ListTextField(models.CharField(max_length=75), blank=True, null=True, size=20),
        ),
    ]
