# Generated by Django 4.2.17 on 2025-05-21 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sadatabase', '0012_alter_application_pre_part_entities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='Pre_Part_Entities',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
