# Generated by Django 4.2.17 on 2025-05-21 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sadatabase', '0013_alter_application_pre_part_entities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='Pre_Part_Entities',
        ),
        migrations.CreateModel(
            name='PreviousParticipantEntities',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('application', models.ManyToManyField(to='sadatabase.application')),
            ],
        ),
    ]
